import type { TikitiEvent } from "./types.ts";

// Already written: sample events. The acts and events are made up.
export const EVENTS: TikitiEvent[] = [
  {
    id: 1,
    title: "Jioni Jazz Night",
    venue: "Uhuru Gardens",
    startsAt: "2026-12-12T18:00:00+03:00",
    priceKes: 2500,
    capacity: 500,
    available: 212,
    status: "published",
    genre: "jazz",
    lineUp: [{ name: "The Jioni Collective", headliner: true }, { name: "Wambui Keys" }, { name: "Brass Matatu" }],
    hue: 265,
  },
  {
    id: 2,
    title: "Gengetone Block Party",
    venue: "Kasarani Annex",
    startsAt: "2026-12-05T15:00:00+03:00",
    priceKes: 800,
    capacity: 1200,
    available: 14,
    status: "published",
    genre: "gengetone",
    lineUp: [{ name: "Mtaa Sound", headliner: true }, { name: "Odi Rider", headliner: true }, { name: "Kaka Bass" }, { name: "DJ Shiko" }],
    hue: 18,
  },
  {
    id: 3,
    title: "Benga Sundowner",
    venue: "Karura Forest Glade",
    startsAt: "2026-12-06T16:30:00+03:00",
    priceKes: 1500,
    capacity: 300,
    available: 0,
    status: "published",
    genre: "benga",
    lineUp: [{ name: "Nyanza Strings", headliner: true }, { name: "Achieng & the Lakeside Band" }],
    hue: 150,
  },
  {
    id: 4,
    title: "Laugh Industry Live",
    venue: "Alliance Française Garden",
    startsAt: "2026-12-10T19:30:00+03:00",
    priceKes: 1000,
    capacity: 250,
    available: 180,
    status: "cancelled",
    genre: "comedy",
    lineUp: [{ name: "Kamau Punchline", headliner: true }, { name: "Nduta Says" }],
    hue: 330,
  },
  {
    id: 5,
    title: "Rhumba Mondays",
    venue: "Mama Njeri's Rooftop",
    startsAt: "2026-12-07T20:00:00+03:00",
    priceKes: 0,
    capacity: 120,
    available: 95,
    status: "published",
    genre: "rhumba",
    lineUp: [],
    hue: 200,
  },
  {
    id: 6,
    title: "Afrobeats in the Park",
    venue: "Central Park, Nairobi",
    startsAt: "2026-12-19T14:00:00+03:00",
    priceKes: 3000,
    capacity: 2000,
    available: 1420,
    status: "published",
    genre: "afrobeats",
    lineUp: [{ name: "Zawadi Waves", headliner: true }, { name: "Lagos to Luthuli" }, { name: "Sheng Soul" }, { name: "Mbogi Brass" }, { name: "DJ Pendo" }],
    hue: 42,
  },
];
