// Writes site/assets/days.js: every day's number, phase, title and one-line brief, read from the
// day folders' READMEs. The site is plain static files, so this list is committed. Run it again
// whenever a day is added or renamed:
//   node scripts/build-site-data.ts          write it
//   node scripts/build-site-data.ts --check  fail if it's out of date (for CI)
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const out = join(root, "site", "assets", "days.js");

// From the course README's table: what each phase teaches and what it ends with.
const PHASES = [
  { n: 1, folder: "phase-1-terminal", name: "Terminal foundations", learn: "variables, types, conditionals, loops, functions, modules", ends: "a text adventure" },
  { n: 2, folder: "phase-2-modelling", name: "Modelling with types", learn: "interfaces, classes, generics, unions, errors, testing", ends: "a CLI money tracker" },
  { n: 3, folder: "phase-3-browser", name: "Browser and games", learn: "the DOM, Vite, Canvas, game loops", ends: "two games you can share" },
  { n: 4, folder: "phase-4-internet", name: "Talking to the internet", learn: "APIs, Zod, secrets, SMS and M-Pesa, scraping", ends: "a daily bot" },
  { n: 5, folder: "phase-5-backend", name: "Backend with Node", learn: "servers, databases, auth, security, tests", ends: "a deployed ticketing API" },
  { n: 6, folder: "phase-6-fullstack-react", name: "Full-stack React", learn: "typed components, forms, data fetching, Next.js", ends: "a ticketing web app" },
  { n: 7, folder: "phase-7-ai", name: "AI in TypeScript", learn: "LLM calls, structured output, tools, retrieval, evals", ends: "a bilingual support agent" },
  { n: 8, folder: "phase-8-portfolio", name: "Portfolio", learn: "no walkthrough: a brief, tests, and you", ends: "20 projects of your own" },
];

interface Day {
  day: number;
  phase: number;
  title: string;
  topic: string; // what it teaches, from the heading after the dash; may be empty
  capstone: boolean;
  path: string; // the day's folder, from the repo root
  brief: string; // the first sentences of "The brief", as plain text
}

// Markdown to plain text, enough for one short paragraph.
const plain = (md: string) =>
  md
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*([^*]*)\*\*/g, "$1")
    .replace(/\*([^*]*)\*/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\s+/g, " ")
    .trim();

function brief(readme: string): string {
  const section = readme.split(/^## The brief\s*$/m)[1] ?? "";
  const paragraph = section.split(/\n\s*\n/).map((p) => p.trim()).find((p) => p && !p.startsWith("```") && !p.startsWith("|") && !p.startsWith("#")) ?? "";
  const text = plain(paragraph);
  if (text.length <= 220) return text;
  const cut = text.slice(0, 220);
  return cut.slice(0, cut.lastIndexOf(" ")).replace(/[,;:]$/, "") + "…";
}

const days: Day[] = [];
for (const phase of PHASES) {
  const phaseDir = join(root, phase.folder);
  for (const folder of readdirSync(phaseDir).filter((f) => /^day-\d{3}-/.test(f)).sort()) {
    const readmePath = join(phaseDir, folder, "README.md");
    if (!existsSync(readmePath)) throw new Error(`${phase.folder}/${folder} has no README.md`);
    const readme = readFileSync(readmePath, "utf8");
    const heading = /^# Day (\d+): (.+)$/m.exec(readme);
    if (!heading) throw new Error(`${phase.folder}/${folder}/README.md doesn't start with "# Day N: Title"`);
    // "Capstone — The Ticketing API" or "Lost in Nairobi CBD — Phase 1 Capstone" both mark a capstone.
    const [left, ...rest] = heading[2].split(" — ");
    const right = rest.join(" — ");
    const capstoneFirst = /^capstone$/i.test(left.trim());
    const capstone = capstoneFirst || /^phase \d+ capstone$/i.test(right.trim());
    days.push({
      day: Number(heading[1]),
      phase: phase.n,
      title: capstoneFirst ? right : left.trim(),
      topic: capstone ? "" : right,
      capstone,
      path: `${phase.folder}/${folder}`,
      brief: brief(readme),
    });
  }
}

days.sort((a, b) => a.day - b.day);
days.forEach((d, i) => {
  if (d.day !== i + 1) throw new Error(`Expected day ${i + 1}, found day ${d.day} at ${d.path}`);
});

const phases = PHASES.map(({ n, name, learn, ends }) => {
  const own = days.filter((d) => d.phase === n);
  return { n, name, learn, ends, first: own[0].day, last: own.at(-1)!.day };
});

const js = `// Generated by scripts/build-site-data.ts from the day folders. Don't edit by hand.
window.TS_PHASES = ${JSON.stringify(phases, null, 2)};

window.TS_DAYS = [
${days.map((d) => `  ${JSON.stringify(d)}`).join(",\n")}
];
`;

if (process.argv.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== js) {
    console.error("site/assets/days.js is out of date. Run: node scripts/build-site-data.ts");
    process.exit(1);
  }
  console.log(`site/assets/days.js is up to date (${days.length} days).`);
} else {
  writeFileSync(out, js);
  console.log(`Wrote ${days.length} days in ${phases.length} phases to site/assets/days.js`);
}
