// Already written: the words. Every answer is a common five-letter Kiswahili word, with its meaning,
// so you learn something from every game. Words with ng' (the apostrophe) are left out, to keep
// every letter a single key.
export const ANSWERS: Record<string, string> = {
  jambo: "hello (a greeting)",
  simba: "lion",
  tembo: "elephant",
  shule: "school",
  barua: "letter (to post)",
  ndizi: "banana",
  wimbo: "song",
  ngoma: "drum; a dance",
  mtoto: "child",
  mlima: "mountain",
  mbuzi: "goat",
  nyoka: "snake",
  twiga: "giraffe",
  punda: "donkey",
  kiatu: "shoe",
  mwaka: "year",
  usiku: "night",
  jioni: "evening",
  ndege: "bird; aeroplane",
  treni: "train",
  mwezi: "moon; month",
  nyota: "star",
  upepo: "wind",
  amani: "peace",
  kesho: "tomorrow",
  kweli: "true; truth",
  mzuri: "good; beautiful",
  mbaya: "bad",
  kubwa: "big",
  ndogo: "small",
  rangi: "colour; paint",
  mkate: "bread",
  ugali: "ugali (maize-meal staple)",
  mboga: "vegetable",
  nyama: "meat",
  tunda: "fruit",
  papai: "papaya",
  swali: "question",
  mgeni: "guest; visitor",
  ukuta: "wall",
  ndoto: "dream",
  picha: "picture; photo",
  redio: "radio",
  mpira: "ball",
  shati: "shirt",
  kofia: "hat",
  mkono: "arm; hand",
  macho: "eyes",
  sikio: "ear",
  mdomo: "mouth",
  mfupa: "bone",
  ngozi: "skin",
  tumbo: "stomach",
  nyati: "buffalo",
  swala: "antelope",
  nyuki: "bee",
  mdudu: "insect",
};

// More real words people may guess, that aren't answers.
export const EXTRA_GUESSES = ["chama", "chupa", "fundi", "sanaa", "shoka", "taifa", "kiazi", "sahau", "zaidi", "kamba"];

export const WORDS = new Set([...Object.keys(ANSWERS), ...EXTRA_GUESSES]);
