// Yours to change: who you are, and what you've built. This sample is a made-up developer, Neema,
// who did this course. Swap in your own projects: the ones from this course count.
import type { SiteConfig } from "./site.ts";

export const site: SiteConfig = {
  name: "Neema Wambui",
  role: "Full-stack TypeScript developer",
  location: "Nairobi, Kenya",
  url: "https://neema.example", // where it will live, with no trailing slash
  basePath: "/", // "/portfolio/" for a GitHub Pages project site at username.github.io/portfolio
  email: "hello@neema.example",
  github: "https://github.com/neema-example",
  intro: "I build fast, friendly web apps in TypeScript: the kind that work on a cheap phone on a slow network, and that people enjoy using.",
  about: [
    "I learned to code by building the things I wished existed in Nairobi: a way to buy event tickets with M-Pesa, a route finder for matatus, a Wordle in Kiswahili.",
    "I care about the details that decide whether software gets used: pages that load on 3G, forms that say what went wrong, and error messages a person can act on. I test the parts that matter and I measure before I optimise.",
    "I'm looking for a junior full-stack role, remote or in Nairobi.",
  ],
};

// Plain data on purpose: site.ts checks it, so a typo shows up as a clear problem, not a broken page.
export const projects: unknown[] = [
  {
    slug: "tikiti",
    title: "Tikiti",
    summary: "Event ticketing with M-Pesa payments, live seat counts and QR check-in at the gate. Next.js, Hono and SQLite.",
    year: 2026,
    featured: true,
    role: "Solo: design, frontend, backend",
    tags: ["Next.js", "React", "Hono", "SQLite", "M-Pesa"],
    links: { live: "https://tikiti.example", source: "https://github.com/neema-example/tikiti" },
    problem: "Small event organisers in Kenya sell tickets through WhatsApp and a spreadsheet. Fans pay by M-Pesa and send a screenshot, and someone at the gate scrolls through messages to check it.",
    approach: "A Next.js site on top of a Hono API. Seats are held for ten minutes while M-Pesa asks the fan's phone for their PIN; the payment callback turns the hold into tickets. Each ticket's QR code is signed, so it can't be forged, and check-in is one atomic update, so a screenshot can't get in at two gates.",
    result: "Every failure path has a test: two fans buying the last seat, duplicate callbacks, wrong amounts, late payments. Pages are server-rendered and under 75 KB of JavaScript on a phone.",
    highlights: ["Seat holds that expire with no clean-up job", "Signed ticket codes: nothing to leak from the database", "Playwright tests for the whole buying journey"],
  },
  {
    slug: "matatu-routes",
    title: "Matatu Route Finder",
    summary: "The quickest way across Nairobi by matatu, with the fewest changes. Dijkstra's algorithm over stages and routes.",
    year: 2026,
    featured: true,
    role: "Solo",
    tags: ["TypeScript", "Algorithms", "Vite"],
    links: { live: "https://matatu.example", source: "https://github.com/neema-example/matatu" },
    problem: "Google Maps knows the roads, not the matatu routes. Asking a tout works, if you know which stage to go to.",
    approach: "The network is a graph of stages. The planner runs Dijkstra over (stage, route) pairs, so a change of matatu costs time: the answer is the quickest trip, and the one with fewer changes when two are close.",
    result: "Answers in under a millisecond, entirely in the browser, and works offline once it's loaded.",
    highlights: ["A binary heap written from scratch", "Plans that prefer fewer changes", "Keyboard-friendly stage search"],
  },
  {
    slug: "neno",
    title: "Neno",
    summary: "A daily five-letter word game in Kiswahili, with streaks, statistics and a share grid.",
    year: 2026,
    featured: true,
    tags: ["TypeScript", "Games", "Kiswahili"],
    links: { live: "https://neno.example", source: "https://github.com/neema-example/neno" },
    problem: "Wordle, but most of my family play in Kiswahili.",
    approach: "The scoring handles repeated letters properly, the puzzle changes at midnight in Nairobi, and statistics live on the device.",
    result: "Played daily by friends and family, and a good lesson in how many edge cases a simple game has.",
    highlights: ["Scoring that gets double letters right", "An on-screen keyboard that remembers colours", "Share results as emoji, with no spoilers"],
  },
  {
    slug: "tikiti-bot",
    title: "Tikiti Discord Bot",
    summary: "Slash commands for events, reminders and gate check-in, right inside a community's Discord server.",
    year: 2026,
    featured: false,
    tags: ["Discord", "Hono", "Security"],
    links: { source: "https://github.com/neema-example/tikiti-bot" },
    problem: "Event communities live in Discord. Fans shouldn't need to leave it to see what's on.",
    approach: "An interactions endpoint that verifies Discord's Ed25519 signature on every request, and answers with embeds, buttons and autocomplete.",
    result: "Gate staff check people in with /checkin, and only they see the answer.",
    highlights: ["Signature checks with replay protection", "Autocomplete for event names"],
  },
  {
    slug: "fupi",
    title: "Fupi",
    summary: "A link shortener with click stats, rate limiting, and links that can't point back at themselves.",
    year: 2026,
    featured: false,
    tags: ["Hono", "SQLite", "Security"],
    links: { live: "https://fupi.example", source: "https://github.com/neema-example/fupi" },
    problem: "I wanted short links for event posters, without handing the clicks to someone else.",
    approach: "A Hono server with SQLite, per-link stats by day and referrer, and checks that refuse unsafe or looping URLs.",
    result: "Runs on a free-tier server and has handled every poster so far.",
    highlights: ["Rate limiting per client", "Stats without storing IP addresses"],
  },
  {
    slug: "slugo-fix",
    title: "Open-source fix: slugo",
    summary: "One root cause behind four bug reports in a slug library, fixed without changing a single existing URL.",
    year: 2026,
    featured: false,
    tags: ["Open source", "TypeScript", "Testing"],
    links: { source: "https://github.com/neema-example/slugo/pull/31" },
    problem: "Emoji made double dashes, maxLength left trailing dashes, and custom separators vanished.",
    approach: "A failing test for each report first. Then I rewrote the core to find words and join them, instead of deleting symbols after the fact.",
    result: "Merged. Every existing test and every real slug stayed the same.",
    highlights: ["Triage: two duplicates and one not-a-bug answered kindly"],
  },
  {
    slug: "season-report",
    title: "Season report, 90x faster",
    summary: "Profiled a slow reporting job and made it 90 times faster with identical output.",
    year: 2026,
    featured: false,
    tags: ["Performance", "TypeScript", "Testing"],
    links: { source: "https://github.com/neema-example/season-report" },
    problem: "The organisers' dashboard timed out building the end-of-season report.",
    approach: "Measured, then profiled: most of the time was creating a date formatter per order, and the rest was searching lists inside loops. One pass with Maps instead.",
    result: "From 1.5 seconds to 17 ms, checked against the original on thousands of generated seasons.",
    highlights: ["A benchmark that also checks the answers match"],
  },
  {
    slug: "trip-splitter",
    title: "Trip Splitter",
    summary: "Split a group trip's costs fairly, down to the last shilling, with the fewest M-Pesa payments to settle up.",
    year: 2026,
    featured: false,
    tags: ["React", "TypeScript", "Money"],
    links: { live: "https://split.example", source: "https://github.com/neema-example/split" },
    problem: "Seven friends, a weekend in Diani, and a spreadsheet nobody trusted.",
    approach: "Money in whole cents, remainders shared out fairly, and a settle-up plan that minimises the number of payments.",
    result: "Used on three trips. Nobody has argued about money since.",
    highlights: ["Never loses or invents a cent"],
  },
];
